name: story-llm-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - faiss-cpu
  - flask
  - click
  - pip
  - eventlet
  - flask-socketio[eventlet]
  - requests
  - prompt_toolkit
  - termcolor
  - websocket-client
  - flask-cors
